name: Derivatives Trader Staging Workflow
on:
  push:
    branches:
    - master
    paths-ignore:
      - "playwright/**"
      - "playwright.config.ts"
      - ".claude/**"

jobs:
  build_test_and_publish:
    name: Build, Test and Publish to Cloudflare Staging
    runs-on: ubuntu-latest
    environment: staging
    permissions:
      contents: read
      actions: write
    steps:
    - name: Checkout
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      with:
        submodules: false
    - name: Setup Node
      uses: "./.github/actions/setup_node"
    - name: Install Dependencies
      uses: "./.github/actions/npm_install_from_cache"
    - name: Build
      uses: "./.github/actions/build"
      with:
        NODE_ENV: staging
        RUDDERSTACK_KEY: ${{ secrets.RUDDERSTACK_KEY }}
        POSTHOG_KEY: ${{ secrets.POSTHOG_KEY }}
        POSTHOG_HOST: ${{ vars.POSTHOG_HOST }}
        REF_NAME: ${{ github.ref_name }}
        R2_PROJECT_NAME: ${{ vars.R2_PROJECT_NAME }}
        CROWDIN_BRANCH_NAME: ${{ vars.CROWDIN_BRANCH_NAME }}
        REMOTE_CONFIG_URL: ${{ vars.REMOTE_CONFIG_URL }}
        # TRUSTPILOT_API_KEY: ${{ secrets.TRUSTPILOT_API_KEY }}
    # - name: Run tests
    #   run: npm test
    - name: Versioning
      uses: "./.github/actions/versioning"
      with:
        release_type: staging
    - name: Publish to Cloudflare Pages Staging
      uses: "./.github/actions/publish_to_pages_staging"
      with:
        CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
